alias: "Boost: Bedroom 3 (Not Blueprint)"
description: ""
triggers:
  - trigger: state
    entity_id:
      - input_select.bedroom_3_climate_state
conditions: []
actions:
  - choose:
      - conditions:
          - condition: state
            entity_id: input_select.bedroom_3_climate_state
            state: Boost Start
        sequence:
          - action: hive.boost_heating_on
            metadata: {}
            data:
              entity_id: climate.bedroom_3_2
              time_period: "01:00:00"
              temperature: 22
      - conditions:
          - condition: state
            entity_id: input_select.bedroom_3_climate_state
            state: Boost End
        sequence:
          - action: hive.boost_heating_off
            metadata: {}
            data:
              entity_id: climate.bedroom_3_2
          - if:
              - condition: state
                entity_id: switch.schedule_office
                state: "on"
            then:
              - action: select.select_option
                metadata: {}
                data:
                  option: "On"
                target:
                  entity_id: input_select.bedroom_3_climate_state
              - data:
                  option: "On"
                action: input_select.select_option
                target:
                  entity_id:
                    - input_select.bedroom_3_climate_state
            else:
              - action: select.select_option
                metadata: {}
                data:
                  option: "Off"
                target:
                  entity_id: input_select.bedroom_3_climate_state
              - data:
                  option: "Off"
                action: input_select.select_option
                target:
                  entity_id:
                    - input_select.bedroom_3_climate_state
      - conditions:
          - condition: state
            entity_id: input_select.bedroom_3_climate_state
            state: "On"
        sequence:
          - action: switch.turn_on
            metadata: {}
            data: {}
            target:
              entity_id: switch.schedule_office
      - conditions:
          - condition: state
            entity_id: input_select.bedroom_3_climate_state
            state: "Off"
        sequence:
          - action: switch.turn_off
            metadata: {}
            data: {}
            target:
              entity_id: switch.schedule_office
mode: single
