blueprint:
  name: Hive TRV Manager
  description: Boost a TRV and manage the associated TRV schedule
  domain: automation
  author: Corneloues
  input:
    trv:
      name: TRV
      description: The TRV to be mnanaged
      selector:
        entity:
          domain: climate
    helper:
      name: Climate Helper
      description: The input_select that has been created with the values 'On', 'Off', 'Boost Start', 'Boost End'
      selector:
        entity:
          domain: input_select
    schedule:
      name: TRV Schedule
      description: The schedule that has been created for the selected TRV
      selector:
        entity:
          integration: scheduler
    script:
      name: TRV Boost Script
      description: The script that has been created to manage a button 'toggle' action
      selector:
        entity:
          domain: script

mode: single
        
triggers:
  platform: state
  entity_id: !input helper

actions:
  - choose:
      - conditions:
          - condition: state
            entity_id: !input helper
            state: Boost Start
        sequence:
          - action: hive.boost_heating_on
            metadata: {}
            data:
              entity_id: !input trv
              time_period: "01:00:00"
              temperature: 22
      - conditions:
          - condition: state
            entity_id: !input helper
            state: Boost End
        sequence:
          - action: hive.boost_heating_off
            metadata: {}
            data:
              entity_id: !input trv
          - if:
              - condition: state
                entity_id: !input schedule
                state: "on"
            then:
              - action: select.select_option
                metadata: {}
                data:
                  option: "On"
                target:
                  entity_id: !input helper
              - data:
                  option: "On"
                action: input_select.select_option
                target:
                  entity_id: !input helper
            else:
              - action: select.select_option
                metadata: {}
                data:
                  option: "Off"
                target:
                  entity_id: !input helper
              - data:
                  option: "Off"
                action: input_select.select_option
                target:
                  entity_id: !input helper
      - conditions:
          - condition: state
            entity_id: !input helper
            state: "On"
        sequence:
          - action: switch.turn_on
            metadata: {}
            data: {}
            target:
              entity_id: !input schedule
      - conditions:
          - condition: state
            entity_id: !input helper
            state: "Off"
        sequence:
          - action: switch.turn_off
            metadata: {}
            data: {}
            target:
              entity_id: !input schedule
