blueprint:
  name: Hue Light Pad
  description: Change the bulb(s) in a given room based on the state of an input_select
  domain: automation
  input:
    room_state:
      name: Room State Helper
      description: An input_select with the necessary options to control the state
      selector:
        entity:
          domain: input_select
    hue_group:
      name: Hue Group
      description: The room as defined in the Hue app
    light_group:
      name: Light Group
      description: The Home Assistant Light Group
      selector:
        entity:
          domain: light
    boolean_effects:
      name: Effects Helper
      description: An input_boolean used by the lovelace card to show/hide the effects
      selector:
        entity:
          domain: input_boolean
    boolean_scenes:
      name: Scenes Helper
      description: An input_boolean used by the lovelace card to show/hide the scenes
      selector:
        entity:
          domain: input_boolean

variables:
  group: !input hue_group

trigger:
  platform: state
  entity_id: !input room_state

action:
  - choose:
      - conditions:
          - condition: state
            entity_id: !input room_state
            state: 'on'
        sequence:
          - service: hue.hue_activate_scene
            data:
              group_name: !input hue_group
              scene_name: Power On
      - conditions:
          - condition: state
            entity_id: !input room_state
            state: bright
        sequence:
          - service: scene.turn_on
            data:
              entity_id: "scene.{{group}}_bright"
          - service: logbook.log
            data:
              name: "{{group}} LightPad"
              message: "Scene set to: scene.{{group}}_bright"
              entity_id: light_group
              domain: automation
      - conditions:
          - condition: state
            entity_id: !input room_state
            state: dim
        sequence:
          - service: hue.hue_activate_scene
            data:
              group_name: !input hue_group
              scene_name: Dimmed
      - conditions:
          - condition: state
            entity_id: !input room_state
            state: night
        sequence:
          - service: hue.hue_activate_scene
            data:
              group_name: !input hue_group
              scene_name: Nightlight
      - conditions:
          - condition: state
            entity_id: !input room_state
            state: relax
        sequence:
          - service: hue.hue_activate_scene
            data:
              group_name: !input hue_group
              scene_name: Relax
      - conditions:
          - condition: state
            entity_id: !input room_state
            state: read
        sequence:
          - service: hue.hue_activate_scene
            data:
              group_name: !input hue_group
              scene_name: Read
      - conditions:
          - condition: state
            entity_id: !input room_state
            state: concentrate
        sequence:
          - service: hue.hue_activate_scene
            data:
              group_name: !input hue_group
              scene_name: Concentrate
      - conditions:
          - condition: state
            entity_id: !input room_state
            state: energize
        sequence:
          - service: hue.hue_activate_scene
            data:
              group_name: !input hue_group
              scene_name: Energize
      - conditions:
          - condition: state
            entity_id: !input room_state
            state: colorloop
        sequence:
          - service: light.turn_on
            data:
              effect: colorloop
              entity_id: !input light_group
      - conditions:
          - condition: state
            entity_id: !input room_state
            state: random
        sequence:
          - service: light.turn_on
            data:
              effect: random
              entity_id: !input light_group
      - conditions:
          - condition: state
            entity_id: !input room_state
            state: repeat
        sequence:
          - service: light.turn_on
            data:
              effect: random
              entity_id: !input light_group
      - conditions:
          - condition: state
            entity_id: !input room_state
            state: sunset
        sequence:
          - service: hue.hue_activate_scene
            data:
              group_name: !input hue_group
              scene_name: Savanna sunset
      - conditions:
          - condition: state
            entity_id: !input room_state
            state: twilight
        sequence:
          - service: hue.hue_activate_scene
            data:
              group_name: !input hue_group
              scene_name: Tropical twilight
      - conditions:
          - condition: state
            entity_id: !input room_state
            state: aurora
        sequence:
          - service: hue.hue_activate_scene
            data:
              group_name: !input hue_group
              scene_name: Arctic aurora
      - conditions:
          - condition: state
            entity_id: !input room_state
            state: blossom
        sequence:
          - service: hue.hue_activate_scene
            data:
              group_name: !input hue_group
              scene_name: Spring blossom
    default:
      - service: input_boolean.turn_off
        data: {}
        entity_id: !input boolean_effects
      - service: input_boolean.turn_off
        data: {}
        entity_id: !input boolean_scenes
      - service: light.turn_off
        data: {}
        entity_id: !input light_group
mode: single